# Generated by Django 4.2 on 2023-04-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
    ]
